name: 'WordPress Plugin Version Bumper'
description: 'Bumps version numbers for WordPress plugins following semantic versioning with prerelease support'
inputs:
  bump_type:
    description: 'Type of version bump to perform (major/minor/patch/build/stable/none)'
    required: true
    default: 'patch'
  prerelease_type:
    description: 'Type of prerelease (none/dev/alpha/beta/rc)'
    required: true
    default: 'none'
  plugin_dir:
    description: 'Directory containing the WordPress plugin'
    required: true
  plugin_main_file:
    description: 'Name of the main plugin file'
    required: true
  surecart_release_file:
    description: 'Path to SureCart release file relative to plugin directory (optional)'
    required: false
outputs:
  new_version:
    description: 'The new version number (e.g., 1.2.3-alpha-1+20240101120000)'
  old_version:
    description: 'The previous version number'
  is_version_bumped:
    description: 'Whether the version was bumped (true/false)'

runs:
  using: 'node20'
  main: 'dist/index.js'
