name: 'WordPress Plugin Version Bumper'
description: 'Bumps version numbers for WordPress plugins following semantic versioning with prerelease support'
inputs:
  bump_type:
    description: 'Type of version bump to perform (none/major/minor/patch/build)'
    required: true
    default: 'patch'
  prerelease_type:
    description: 'Type of prerelease (none/dev/alpha/beta/rc)'
    required: true
    default: 'none'
  plugin_dir:
    description: 'Directory containing the WordPress plugin'
    required: true
  main_file:
    description: 'Name of the main plugin file'
    required: true
outputs:
  new_version:
    description: 'The new version number'
  old_version:
    description: 'The previous version number'
  is_version_bumped:
    description: 'Whether the version was bumped'

runs:
  using: 'node20'
  main: 'index.js'
