name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          if-no-files-found: error

  test-action:
    name: Test action execution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install all dependencies
        run: npm ci

      - name: Build action
        run: npm run build

      - name: Install production dependencies
        run: |
          npm ci --only=production
          rm -rf node_modules/@vercel/ncc

      - name: Test major bump
        uses: ./
        with:
          bump_type: 'major'
          prerelease_type: 'none'
          plugin_dir: 'test/fixtures'
          plugin_main_file: 'test-plugin.php'

      - name: Test patch with beta
        uses: ./
        with:
          bump_type: 'patch'
          prerelease_type: 'beta'
          plugin_dir: 'test/fixtures'
          plugin_main_file: 'test-plugin.php'

      - name: Test build number
        uses: ./
        with:
          bump_type: 'build'
          prerelease_type: 'none'
          plugin_dir: 'test/fixtures'
          plugin_main_file: 'test-plugin.php'
