# .github/workflows/test.yml
name: Test WordPress Plugin Version Bump Action
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create test plugin file
        run: |
          mkdir -p test
          echo "* Version: 1.2.3" > test/plugin.php

      # Test version bump true case
      - name: Test patch release
        id: patch_release
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: Stable
          version_bump: Patch

      - name: Verify patch release and version_bumped true
        run: |
          version=$(grep -e 'Version:' test/plugin.php | grep -oP '\d+\.\d+\.\d+')
          [[ "$version" == "1.2.4" ]] || exit 1
          [[ "${{ steps.patch_release.outputs.version_bumped }}" == "true" ]] || exit 1

      # Test version bump false case
      - name: Reset test file
        run: |
          echo "* Version: 1.2.3" > test/plugin.php

      - name: Test no version bump
        id: no_bump
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: Stable
          version_bump: No version bump

      - name: Verify no version bump and version_bumped false
        run: |
          version=$(grep -e 'Version:' test/plugin.php | grep -oP '\d+\.\d+\.\d+')
          [[ "$version" == "1.2.3" ]] || exit 1
          [[ "${{ steps.no_bump.outputs.version_bumped }}" == "false" ]] || exit 1

      - name: Reset test file for minor release
        run: |
          echo "* Version: 1.2.3" > test/plugin.php

      - name: Test minor release
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: Stable
          version_bump: Minor

      - name: Verify minor release
        run: |
          version=$(grep -e 'Version:' test/plugin.php | grep -oP '\d+\.\d+\.\d+')
          [[ "$version" == "1.3.0" ]] || exit 1

      - name: Reset test file for major release
        run: |
          echo "* Version: 1.2.3" > test/plugin.php

      - name: Test major release
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: Stable
          version_bump: Major

      - name: Verify major release
        run: |
          version=$(grep -e 'Version:' test/plugin.php | grep -oP '\d+\.\d+\.\d+')
          [[ "$version" == "2.0.0" ]] || exit 1

      - name: Reset test file for alpha release with patch
        run: |
          echo "* Version: 1.2.3" > test/plugin.php

      - name: Test alpha release with patch
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: Alpha
          version_bump: Patch

      - name: Verify alpha release with patch
        run: |
          version=$(grep -e 'Version:' test/plugin.php | grep -oP '\d+\.\d+\.\d+(-alpha-\d+)?')
          [[ "$version" == "1.2.4-alpha-1" ]] || exit 1

      - name: Reset test file for alpha increment
        run: |
          echo "* Version: 1.2.3-alpha-1" > test/plugin.php

      - name: Test alpha increment
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: Alpha
          version_bump: No version bump

      - name: Verify alpha increment
        run: |
          version=$(grep -e 'Version:' test/plugin.php | grep -oP '\d+\.\d+\.\d+(-alpha-\d+)?')
          [[ "$version" == "1.2.3-alpha-2" ]] || exit 1

      - name: Reset test file for alpha to beta transition
        run: |
          echo "* Version: 0.0.21-alpha-1" > test/plugin.php

      - name: Test alpha to beta transition
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: Beta
          version_bump: No version bump

      - name: Verify alpha to beta transition
        run: |
          version=$(grep -e 'Version:' test/plugin.php | grep -oP '\d+\.\d+\.\d+(-beta-\d+)?')
          [[ "$version" == "0.0.21-beta-1" ]] || exit 1

      - name: Reset test file for beta to rc transition
        run: |
          echo "* Version: 0.0.21-beta-1" > test/plugin.php

      - name: Test beta to rc transition
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: RC
          version_bump: No version bump

      - name: Verify beta to rc transition
        run: |
          version=$(grep -e 'Version:' test/plugin.php | grep -oP '\d+\.\d+\.\d+(-rc-\d+)?')
          [[ "$version" == "0.0.21-rc-1" ]] || exit 1

      - name: Reset test file for build release
        run: |
          echo "* Version: 1.2.3" > test/plugin.php

      - name: Test build release
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: Stable
          version_bump: Build

      - name: Verify build release
        run: |
          version=$(grep -e 'Version:' test/plugin.php)
          [[ "$version" =~ 1\.2\.3\+[0-9]{14}-[0-9]+$ ]] || exit 1

      - name: Reset test file for build release with prerelease
        run: |
          echo "* Version: 1.2.3-alpha-1" > test/plugin.php

      - name: Test build release with prerelease
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: Alpha
          version_bump: Build

      - name: Verify build release with prerelease
        run: |
          version=$(grep -e 'Version:' test/plugin.php)
          [[ "$version" =~ 1\.2\.3-alpha-1\+[0-9]{14}-[0-9]+$ ]] || exit 1

      - name: Reset test file for prerelease to stable
        run: |
          echo "* Version: 0.0.21-alpha-1" > test/plugin.php

      - name: Test prerelease to stable
        uses: ./
        with:
          plugin_file_path: test/plugin.php
          release_type: Stable
          version_bump: No version bump

      - name: Verify prerelease to stable
        run: |
          version=$(grep -e 'Version:' test/plugin.php | grep -oP '\d+\.\d+\.\d+')
          [[ "$version" == "0.0.21" ]] || exit 1

      # Test custom version line pattern
      - name: Create test file with custom version pattern
        run: |
          echo "* Plugin Version: 1.2.3" > test/custom-plugin.php

      - name: Test custom version pattern
        uses: ./
        with:
          plugin_file_path: test/custom-plugin.php
          version_line_pattern: "Plugin Version:"
          release_type: Stable
          version_bump: Patch

      - name: Verify custom version pattern
        run: |
          version=$(grep -e 'Plugin Version:' test/custom-plugin.php | grep -oP '\d+\.\d+\.\d+')
          [[ "$version" == "1.2.4" ]] || exit 1
